// <auto-generated />
using System;
using AgencyWebApp.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AgencyWebApp.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260324100252_InitialRussianSeed")]
    partial class InitialRussianSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AgencyWebApp.Domain.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FlightId")
                        .HasColumnType("int");

                    b.Property<int?>("HotelId")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<int?>("TourId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FlightId");

                    b.HasIndex("HotelId");

                    b.HasIndex("TourId");

                    b.HasIndex("UserId");

                    b.ToTable("Bookings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookingDate = new DateTime(2026, 1, 10, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            HotelId = 7,
                            Status = true,
                            TourId = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            BookingDate = new DateTime(2026, 1, 12, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            HotelId = 1,
                            Status = true,
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            BookingDate = new DateTime(2026, 1, 14, 9, 15, 0, 0, DateTimeKind.Unspecified),
                            FlightId = 1,
                            Status = false,
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            BookingDate = new DateTime(2026, 1, 15, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            HotelId = 2,
                            Status = true,
                            TourId = 4,
                            UserId = 4
                        },
                        new
                        {
                            Id = 5,
                            BookingDate = new DateTime(2026, 1, 16, 16, 45, 0, 0, DateTimeKind.Unspecified),
                            HotelId = 2,
                            Status = true,
                            UserId = 5
                        },
                        new
                        {
                            Id = 6,
                            BookingDate = new DateTime(2026, 1, 17, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            HotelId = 9,
                            Status = true,
                            TourId = 9,
                            UserId = 6
                        },
                        new
                        {
                            Id = 7,
                            BookingDate = new DateTime(2026, 1, 18, 18, 20, 0, 0, DateTimeKind.Unspecified),
                            HotelId = 4,
                            Status = true,
                            TourId = 2,
                            UserId = 7
                        },
                        new
                        {
                            Id = 8,
                            BookingDate = new DateTime(2026, 1, 19, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            FlightId = 3,
                            Status = false,
                            UserId = 8
                        },
                        new
                        {
                            Id = 9,
                            BookingDate = new DateTime(2026, 1, 20, 13, 10, 0, 0, DateTimeKind.Unspecified),
                            HotelId = 10,
                            Status = true,
                            TourId = 5,
                            UserId = 9
                        },
                        new
                        {
                            Id = 10,
                            BookingDate = new DateTime(2026, 1, 20, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            HotelId = 3,
                            Status = true,
                            TourId = 10,
                            UserId = 10
                        });
                });

            modelBuilder.Entity("AgencyWebApp.Domain.Models.Flight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AirPlaneName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("ArrivalTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DepartureTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("FlightNumber")
                        .HasColumnType("int");

                    b.Property<string>("FromCity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("FromLatitude")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("FromLongitude")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ToCity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ToLatitude")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ToLongitude")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Flights");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AirPlaneName = "Boeing 737-800",
                            ArrivalTime = new DateTime(2026, 5, 10, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = new DateTime(2026, 5, 10, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            FlightNumber = 101,
                            FromCity = "Москва (DME)",
                            FromLatitude = 55.4103m,
                            FromLongitude = 37.9024m,
                            Price = 250.00m,
                            Status = "Запланирован",
                            ToCity = "Душанбе (DYU)",
                            ToLatitude = 38.5433m,
                            ToLongitude = 68.8249m
                        },
                        new
                        {
                            Id = 2,
                            AirPlaneName = "Airbus A320",
                            ArrivalTime = new DateTime(2026, 5, 12, 16, 15, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = new DateTime(2026, 5, 12, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            FlightNumber = 202,
                            FromCity = "Истанбул (IST)",
                            FromLatitude = 41.2753m,
                            FromLongitude = 28.7519m,
                            Price = 320.00m,
                            Status = "Запланирован",
                            ToCity = "Душанбе (DYU)",
                            ToLatitude = 38.5433m,
                            ToLongitude = 68.8249m
                        },
                        new
                        {
                            Id = 3,
                            AirPlaneName = "Boeing 737-300",
                            ArrivalTime = new DateTime(2026, 5, 15, 8, 50, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = new DateTime(2026, 5, 15, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            FlightNumber = 303,
                            FromCity = "Душанбе (DYU)",
                            FromLatitude = 38.5433m,
                            FromLongitude = 68.8249m,
                            Price = 45.00m,
                            Status = "Активный",
                            ToCity = "Худжанд (LBD)",
                            ToLatitude = 40.2152m,
                            ToLongitude = 69.6944m
                        },
                        new
                        {
                            Id = 4,
                            AirPlaneName = "Boeing 737-800",
                            ArrivalTime = new DateTime(2026, 5, 19, 2, 30, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = new DateTime(2026, 5, 18, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            FlightNumber = 404,
                            FromCity = "Дубай (DXB)",
                            FromLatitude = 25.2532m,
                            FromLongitude = 55.3657m,
                            Price = 380.00m,
                            Status = "Запланирован",
                            ToCity = "Душанбе (DYU)",
                            ToLatitude = 38.5433m,
                            ToLongitude = 68.8249m
                        },
                        new
                        {
                            Id = 5,
                            AirPlaneName = "Airbus A321",
                            ArrivalTime = new DateTime(2026, 5, 20, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = new DateTime(2026, 5, 20, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            FlightNumber = 505,
                            FromCity = "Ташкент (TAS)",
                            FromLatitude = 41.2575m,
                            FromLongitude = 69.2817m,
                            Price = 110.00m,
                            Status = "Активный",
                            ToCity = "Душанбе (DYU)",
                            ToLatitude = 38.5433m,
                            ToLongitude = 68.8249m
                        },
                        new
                        {
                            Id = 6,
                            AirPlaneName = "Boeing 737-800",
                            ArrivalTime = new DateTime(2026, 5, 22, 11, 45, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = new DateTime(2026, 5, 22, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            FlightNumber = 606,
                            FromCity = "Алматы (ALA)",
                            FromLatitude = 43.3520m,
                            FromLongitude = 77.0115m,
                            Price = 140.00m,
                            Status = "Запланирован",
                            ToCity = "Душанбе (DYU)",
                            ToLatitude = 38.5433m,
                            ToLongitude = 68.8249m
                        },
                        new
                        {
                            Id = 7,
                            AirPlaneName = "Boeing 787 Dreamliner",
                            ArrivalTime = new DateTime(2026, 5, 26, 6, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = new DateTime(2026, 5, 25, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            FlightNumber = 707,
                            FromCity = "Франкфурт (FRA)",
                            FromLatitude = 50.0333m,
                            FromLongitude = 8.5705m,
                            Price = 650.00m,
                            Status = "Задержан",
                            ToCity = "Душанбе (DYU)",
                            ToLatitude = 38.5433m,
                            ToLongitude = 68.8249m
                        },
                        new
                        {
                            Id = 8,
                            AirPlaneName = "Airbus A320",
                            ArrivalTime = new DateTime(2026, 5, 28, 7, 30, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = new DateTime(2026, 5, 28, 4, 0, 0, 0, DateTimeKind.Unspecified),
                            FlightNumber = 808,
                            FromCity = "Дели (DEL)",
                            FromLatitude = 28.5562m,
                            FromLongitude = 77.1000m,
                            Price = 290.00m,
                            Status = "Запланирован",
                            ToCity = "Душанбе (DYU)",
                            ToLatitude = 38.5433m,
                            ToLongitude = 68.8249m
                        },
                        new
                        {
                            Id = 9,
                            AirPlaneName = "Boeing 737-800",
                            ArrivalTime = new DateTime(2026, 6, 1, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = new DateTime(2026, 6, 1, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            FlightNumber = 909,
                            FromCity = "Мюнхен (MUC)",
                            FromLatitude = 48.3537m,
                            FromLongitude = 11.7750m,
                            Price = 580.00m,
                            Status = "Активный",
                            ToCity = "Душанбе (DYU)",
                            ToLatitude = 38.5433m,
                            ToLongitude = 68.8249m
                        },
                        new
                        {
                            Id = 10,
                            AirPlaneName = "Embraer 190",
                            ArrivalTime = new DateTime(2026, 6, 3, 17, 30, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = new DateTime(2026, 6, 3, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            FlightNumber = 110,
                            FromCity = "Урумчи (URC)",
                            FromLatitude = 43.9071m,
                            FromLongitude = 87.4742m,
                            Price = 420.00m,
                            Status = "Запланирован",
                            ToCity = "Душанбе (DYU)",
                            ToLatitude = 38.5433m,
                            ToLongitude = 68.8249m
                        });
                });

            modelBuilder.Entity("AgencyWebApp.Domain.Models.Hotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Hotels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "проспект Рудаки, 14",
                            City = "Душанбе",
                            Country = "Таджикистан",
                            Description = "Роскошный 5-звездочный отель в самом сердце столицы, выполненный в традиционном таджикском стиле.",
                            Latitude = 38.5737m,
                            Longitude = 68.7938m,
                            Name = "Dushanbe Serena Hotel",
                            PhotoUrl = "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=800",
                            Price = 160.00m,
                            Rating = 5,
                            Status = false
                        },
                        new
                        {
                            Id = 2,
                            Address = "проспект Исмоили Сомони, 26/1",
                            City = "Душанбе",
                            Country = "Таджикистан",
                            Description = "Современный отель на берегу озера, идеально подходящий как для деловых поездок, так и для отдыха.",
                            Latitude = 38.5858m,
                            Longitude = 68.7725m,
                            Name = "Hyatt Regency Dushanbe",
                            PhotoUrl = "https://images.unsplash.com/photo-1551882547-ff43c63e1c04?auto=format&fit=crop&w=800",
                            Price = 185.00m,
                            Rating = 5,
                            Status = false
                        },
                        new
                        {
                            Id = 3,
                            Address = "ул. Нисора Мухаммада, 63",
                            City = "Душанбе",
                            Country = "Таджикистан",
                            Description = "Бутик-отель, оформленный с использованием национальных тканей и располагающий прекрасным садом.",
                            Latitude = 38.5601m,
                            Longitude = 68.8120m,
                            Name = "Atlas Hotel",
                            PhotoUrl = "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?auto=format&fit=crop&w=800",
                            Price = 85.00m,
                            Rating = 4,
                            Status = false
                        },
                        new
                        {
                            Id = 4,
                            Address = "ул. Камоли Худжанди, 22",
                            City = "Худжанд",
                            Country = "Таджикистан",
                            Description = "Лучшие апартаменты в центре Худжанда с великолепным видом на реку Сырдарья.",
                            Latitude = 40.2825m,
                            Longitude = 69.6221m,
                            Name = "Armon Aparthotel",
                            PhotoUrl = "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=800",
                            Price = 75.00m,
                            Rating = 4,
                            Status = false
                        },
                        new
                        {
                            Id = 5,
                            Address = "ул. Ленина, 15",
                            City = "Худжанд",
                            Country = "Таджикистан",
                            Description = "Классический отель, расположенный рядом с историческим рынком Панджшанбе.",
                            Latitude = 40.2790m,
                            Longitude = 69.6300m,
                            Name = "Sugdiyon Hotel",
                            PhotoUrl = "https://images.unsplash.com/photo-1561501900-3701fa6a0864?auto=format&fit=crop&w=800",
                            Price = 55.00m,
                            Rating = 3,
                            Status = false
                        },
                        new
                        {
                            Id = 6,
                            Address = "поселок Калайхумб",
                            City = "Дарвоз",
                            Country = "Таджикистан",
                            Description = "Ворота Памира. Роскошный комфорт в окружении величественных диких гор.",
                            Latitude = 38.4571m,
                            Longitude = 70.7831m,
                            Name = "Karon Palace",
                            PhotoUrl = "https://images.unsplash.com/photo-1445019980597-93fa8acb246c?auto=format&fit=crop&w=800",
                            Price = 95.00m,
                            Rating = 5,
                            Status = false
                        },
                        new
                        {
                            Id = 7,
                            Address = "ул. Ленина, 52",
                            City = "Хорог",
                            Country = "Таджикистан",
                            Description = "Знаменитый памирский гостевой дом, известный своим гостеприимством и традиционной кухней.",
                            Latitude = 37.4896m,
                            Longitude = 71.5511m,
                            Name = "Lal Hotel",
                            PhotoUrl = "https://images.unsplash.com/photo-1582719478250-c89cae4df85b?auto=format&fit=crop&w=800",
                            Price = 65.00m,
                            Rating = 4,
                            Status = false
                        },
                        new
                        {
                            Id = 8,
                            Address = "проспект Вахдат, 10",
                            City = "Бохтар",
                            Country = "Таджикистан",
                            Description = "Комфортабельный отель в центре города, удобный для путешественников, изучающих Хатлонскую область.",
                            Latitude = 37.8364m,
                            Longitude = 68.7802m,
                            Name = "Grand Hotel Bokhtar",
                            PhotoUrl = "https://images.unsplash.com/photo-1495365200479-c4ed1d35e1aa?auto=format&fit=crop&w=800",
                            Price = 60.00m,
                            Rating = 3,
                            Status = false
                        },
                        new
                        {
                            Id = 9,
                            Address = "ул. Лоика Шерали, 3",
                            City = "Душанбе",
                            Country = "Таджикистан",
                            Description = "Уютный и тихий бутик-отель, расположенный в элитном жилом районе столицы.",
                            Latitude = 38.5900m,
                            Longitude = 68.7850m,
                            Name = "Seven In Boutique",
                            PhotoUrl = "https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=800",
                            Price = 90.00m,
                            Rating = 4,
                            Status = false
                        },
                        new
                        {
                            Id = 10,
                            Address = "ул. Айни, 48",
                            City = "Душанбе",
                            Country = "Таджикистан",
                            Description = "Сервис премиум-класса вблизи аэропорта и центральной части Душанбе.",
                            Latitude = 38.5672m,
                            Longitude = 68.8051m,
                            Name = "Hilton Dushanbe",
                            PhotoUrl = "https://images.unsplash.com/photo-1590490360182-c33d57733427?auto=format&fit=crop&w=800",
                            Price = 145.00m,
                            Rating = 5,
                            Status = false
                        });
                });

            modelBuilder.Entity("AgencyWebApp.Domain.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FlightId")
                        .HasColumnType("int");

                    b.Property<int?>("HotelId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("TourId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FlightId");

                    b.HasIndex("HotelId");

                    b.HasIndex("TourId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HotelId = 7,
                            Text = "Путешествие по Памирскому тракту изменило мою жизнь! Очень рекомендую всем любителям гор.",
                            TourId = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 12, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HotelId = 1,
                            Text = "Отель Dushanbe Serena — лучшее место для проживания. Очень профессиональный и вежливый персонал.",
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FlightId = 1,
                            Text = "Рейс из Москвы в Душанбе прошел вовремя, полет был очень комфортным. Спасибо!",
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HotelId = 2,
                            Text = "Озеро Искандеркуль просто захватывает дух. Наш гид рассказал много интересных легенд.",
                            TourId = 4,
                            UserId = 4
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HotelId = 2,
                            Text = "Отличный сервис в Hyatt Regency. Выбор блюд на завтрак был просто потрясающим.",
                            UserId = 5
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HotelId = 9,
                            Text = "Крепость Хулбук — это настоящая скрытая жемчужина Хатлона. Обязательно к посещению для любителей истории.",
                            TourId = 9,
                            UserId = 6
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HotelId = 4,
                            Text = "Руины Пенджикента впечатляют. Тур по Семи озерам немного утомительный, но он того стоит!",
                            TourId = 2,
                            UserId = 7
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FlightId = 3,
                            Text = "Перелет Somon Air в Худжанд был быстрым и спокойным. Никаких нареканий.",
                            UserId = 8
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2026, 1, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HotelId = 10,
                            Text = "Санаторий в Ходжа-Обигарм — уникальное место. Идеально подходит для оздоровления и релаксации.",
                            TourId = 5,
                            UserId = 9
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HotelId = 3,
                            Text = "Классная поездка в Варзобское ущелье на выходные. Отличный способ сбежать от городской жары!",
                            TourId = 10,
                            UserId = 10
                        });
                });

            modelBuilder.Entity("AgencyWebApp.Domain.Models.Tour", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("StartLatitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal>("StartLongitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Tours");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Легендарное путешествие по высокогорным дорогам Памира с посещением города Хорог.",
                            Duration = 7,
                            PhotoUrl = "https://images.unsplash.com/photo-1581414441460-7058866e409b?auto=format&fit=crop&w=800",
                            Price = 550.00m,
                            Rating = 5,
                            Region = "ГБАО",
                            StartLatitude = 38.5737m,
                            StartLongitude = 68.7938m,
                            Status = true,
                            Title = "Приключение на Памирском тракте"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Исследуйте руины Саразма и невероятные Семь озер (Хафт-Кул).",
                            Duration = 3,
                            PhotoUrl = "https://images.unsplash.com/photo-1541829070764-84a7d30dee6b?auto=format&fit=crop&w=800",
                            Price = 120.00m,
                            Rating = 5,
                            Region = "Согдийская область",
                            StartLatitude = 39.4969m,
                            StartLongitude = 67.6103m,
                            Status = true,
                            Title = "Древний Пенджикент и озера"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Посещение Национального музея, памятника Исмоили Сомони и колоритных местных базаров.",
                            Duration = 2,
                            PhotoUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/National_Museum_of_Tajikistan.jpg/800px-National_Museum_of_Tajikistan.jpg",
                            Price = 85.00m,
                            Rating = 4,
                            Region = "Душанбе",
                            StartLatitude = 38.5858m,
                            StartLongitude = 68.7725m,
                            Status = true,
                            Title = "Выходные в Душанбе"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Посетите легендарное озеро Александра Македонского и знаменитый водопад «Фанская Ниагара».",
                            Duration = 3,
                            PhotoUrl = "https://images.unsplash.com/photo-1563290328-9710279603e8?auto=format&fit=crop&w=800",
                            Price = 150.00m,
                            Rating = 5,
                            Region = "Фанские горы",
                            StartLatitude = 39.0833m,
                            StartLongitude = 68.3667m,
                            Status = true,
                            Title = "Побег к озеру Искандеркуль"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Отдых и лечение в знаменитом бальнеологическом санатории с уникальными термальными парами.",
                            Duration = 10,
                            PhotoUrl = "https://images.unsplash.com/photo-1544161515-4ab6ce6db874?auto=format&fit=crop&w=800",
                            Price = 300.00m,
                            Rating = 4,
                            Region = "Варзоб",
                            StartLatitude = 38.8953m,
                            StartLongitude = 68.7914m,
                            Status = true,
                            Title = "Оздоровление в Ходжа-Обигарм"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Жизнь кочевников, яки и фантастические «лунные» ландшафты высокогорья у границы с Китаем.",
                            Duration = 12,
                            PhotoUrl = "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=800",
                            Price = 750.00m,
                            Rating = 5,
                            Region = "Восточный Памир",
                            StartLatitude = 38.1702m,
                            StartLongitude = 73.9647m,
                            Status = true,
                            Title = "Мургаб: Крыша мира"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Исторический тур в крепость V века и прогулка по живописному берегу Сырдарьи.",
                            Duration = 2,
                            PhotoUrl = "https://images.unsplash.com/photo-1523393160341-9c869066666d?auto=format&fit=crop&w=800",
                            Price = 90.00m,
                            Rating = 4,
                            Region = "Согдийская область",
                            StartLatitude = 40.2825m,
                            StartLongitude = 69.6221m,
                            Status = true,
                            Title = "Тур в Худжандскую крепость"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Эко-тур в одну из самых красивых и отдаленных долин Таджикистана.",
                            Duration = 5,
                            PhotoUrl = "https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=800",
                            Price = 210.00m,
                            Rating = 5,
                            Region = "Хатлон",
                            StartLatitude = 38.2167m,
                            StartLongitude = 69.8333m,
                            Status = true,
                            Title = "Природа Сари-Хосор"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Однодневная поездка в реконструированный дворец средневековых царей Хутталя.",
                            Duration = 1,
                            PhotoUrl = "https://images.unsplash.com/photo-1590059132218-22ca52103723?auto=format&fit=crop&w=800",
                            Price = 45.00m,
                            Rating = 4,
                            Region = "Хатлон",
                            StartLatitude = 37.7772m,
                            StartLongitude = 69.5539m,
                            Status = true,
                            Title = "История крепости Хулбук"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Самая популярная зона отдыха рядом с Душанбе: реки, горы и свежий воздух.",
                            Duration = 1,
                            PhotoUrl = "https://images.unsplash.com/photo-1470770841072-f978cf4d019e?auto=format&fit=crop&w=800",
                            Price = 35.00m,
                            Rating = 5,
                            Region = "РРП",
                            StartLatitude = 38.7411m,
                            StartLongitude = 68.8144m,
                            Status = true,
                            Title = "День в Варзобском ущелье"
                        });
                });

            modelBuilder.Entity("AgencyWebApp.Domain.Models.TourPoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Latitude")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int>("TourId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TourId");

                    b.ToTable("TourPoint");
                });

            modelBuilder.Entity("AgencyWebApp.Domain.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("HomeLatitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal?>("HomeLongitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "alisher@mail.tj",
                            FullName = "Алишер Саидов",
                            Password = "$2a$11$J4K9KM.WmiU9dnll1wfQP.vfReR76JPUgd8ostD2oOekk1/gNxPpG",
                            Role = 1
                        },
                        new
                        {
                            Id = 2,
                            Email = "madina@gmail.com",
                            FullName = "Мадина Каримова",
                            Password = "$2a$11$J4K9KM.WmiU9dnll1wfQP.vfReR76JPUgd8ostD2oOekk1/gNxPpG",
                            Role = 1
                        },
                        new
                        {
                            Id = 3,
                            Email = "bakhtier@list.ru",
                            FullName = "Бахтиёр Назаров",
                            Password = "$2a$11$J4K9KM.WmiU9dnll1wfQP.vfReR76JPUgd8ostD2oOekk1/gNxPpG",
                            Role = 1
                        },
                        new
                        {
                            Id = 4,
                            Email = "nigina@yandex.ru",
                            FullName = "Нигина Рахимова",
                            Password = "$2a$11$J4K9KM.WmiU9dnll1wfQP.vfReR76JPUgd8ostD2oOekk1/gNxPpG",
                            Role = 1
                        },
                        new
                        {
                            Id = 5,
                            Email = "parviz@outlook.com",
                            FullName = "Парвиз Ходжаев",
                            Password = "$2a$11$J4K9KM.WmiU9dnll1wfQP.vfReR76JPUgd8ostD2oOekk1/gNxPpG",
                            Role = 1
                        },
                        new
                        {
                            Id = 6,
                            Email = "zarina@mail.tj",
                            FullName = "Зарина Олимова",
                            Password = "$2a$11$J4K9KM.WmiU9dnll1wfQP.vfReR76JPUgd8ostD2oOekk1/gNxPpG",
                            Role = 1
                        },
                        new
                        {
                            Id = 7,
                            Email = "rustam@google.com",
                            FullName = "Рустам Эшонов",
                            Password = "$2a$11$J4K9KM.WmiU9dnll1wfQP.vfReR76JPUgd8ostD2oOekk1/gNxPpG",
                            Role = 1
                        },
                        new
                        {
                            Id = 8,
                            Email = "sitora@inbox.ru",
                            FullName = "Ситора Джумаева",
                            Password = "$2a$11$J4K9KM.WmiU9dnll1wfQP.vfReR76JPUgd8ostD2oOekk1/gNxPpG",
                            Role = 1
                        },
                        new
                        {
                            Id = 9,
                            Email = "firdavs@rambler.ru",
                            FullName = "Фирдавс Гафуров",
                            Password = "$2a$11$J4K9KM.WmiU9dnll1wfQP.vfReR76JPUgd8ostD2oOekk1/gNxPpG",
                            Role = 1
                        },
                        new
                        {
                            Id = 10,
                            Email = "lola@tj-travel.tj",
                            FullName = "Лола Шарипова",
                            Password = "$2a$11$J4K9KM.WmiU9dnll1wfQP.vfReR76JPUgd8ostD2oOekk1/gNxPpG",
                            Role = 1
                        });
                });

            modelBuilder.Entity("AgencyWebApp.Domain.Models.Booking", b =>
                {
                    b.HasOne("AgencyWebApp.Domain.Models.Flight", "Flight")
                        .WithMany("Bookings")
                        .HasForeignKey("FlightId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AgencyWebApp.Domain.Models.Hotel", "Hotel")
                        .WithMany("Bookings")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AgencyWebApp.Domain.Models.Tour", "Tour")
                        .WithMany("Bookings")
                        .HasForeignKey("TourId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AgencyWebApp.Domain.Models.User", "User")
                        .WithMany("Bookings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Flight");

                    b.Navigation("Hotel");

                    b.Navigation("Tour");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AgencyWebApp.Domain.Models.Review", b =>
                {
                    b.HasOne("AgencyWebApp.Domain.Models.Flight", "Flight")
                        .WithMany("Reviews")
                        .HasForeignKey("FlightId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AgencyWebApp.Domain.Models.Hotel", "Hotel")
                        .WithMany("Reviews")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AgencyWebApp.Domain.Models.Tour", "Tour")
                        .WithMany("Reviews")
                        .HasForeignKey("TourId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AgencyWebApp.Domain.Models.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Flight");

                    b.Navigation("Hotel");

                    b.Navigation("Tour");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AgencyWebApp.Domain.Models.TourPoint", b =>
                {
                    b.HasOne("AgencyWebApp.Domain.Models.Tour", "Tour")
                        .WithMany("TourPoints")
                        .HasForeignKey("TourId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tour");
                });

            modelBuilder.Entity("AgencyWebApp.Domain.Models.Flight", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("AgencyWebApp.Domain.Models.Hotel", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("AgencyWebApp.Domain.Models.Tour", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Reviews");

                    b.Navigation("TourPoints");
                });

            modelBuilder.Entity("AgencyWebApp.Domain.Models.User", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
