// <auto-generated />
using System;
using AgencyWebApp.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AgencyWebApp.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260123054928_AddStatusFieldToTables")]
    partial class AddStatusFieldToTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AgencyWebApp.Domain.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FlightId")
                        .HasColumnType("int");

                    b.Property<int?>("HotelId")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<int?>("TourId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FlightId");

                    b.HasIndex("HotelId");

                    b.HasIndex("TourId");

                    b.HasIndex("UserId");

                    b.ToTable("Bookings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookingDate = new DateTime(2026, 1, 10, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            HotelId = 7,
                            Status = true,
                            TourId = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            BookingDate = new DateTime(2026, 1, 12, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            HotelId = 1,
                            Status = true,
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            BookingDate = new DateTime(2026, 1, 14, 9, 15, 0, 0, DateTimeKind.Unspecified),
                            FlightId = 1,
                            Status = false,
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            BookingDate = new DateTime(2026, 1, 15, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            HotelId = 2,
                            Status = true,
                            TourId = 4,
                            UserId = 4
                        },
                        new
                        {
                            Id = 5,
                            BookingDate = new DateTime(2026, 1, 16, 16, 45, 0, 0, DateTimeKind.Unspecified),
                            HotelId = 2,
                            Status = true,
                            UserId = 5
                        },
                        new
                        {
                            Id = 6,
                            BookingDate = new DateTime(2026, 1, 17, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            HotelId = 9,
                            Status = true,
                            TourId = 9,
                            UserId = 6
                        },
                        new
                        {
                            Id = 7,
                            BookingDate = new DateTime(2026, 1, 18, 18, 20, 0, 0, DateTimeKind.Unspecified),
                            HotelId = 4,
                            Status = true,
                            TourId = 2,
                            UserId = 7
                        },
                        new
                        {
                            Id = 8,
                            BookingDate = new DateTime(2026, 1, 19, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            FlightId = 3,
                            Status = false,
                            UserId = 8
                        },
                        new
                        {
                            Id = 9,
                            BookingDate = new DateTime(2026, 1, 20, 13, 10, 0, 0, DateTimeKind.Unspecified),
                            HotelId = 10,
                            Status = true,
                            TourId = 5,
                            UserId = 9
                        },
                        new
                        {
                            Id = 10,
                            BookingDate = new DateTime(2026, 1, 20, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            HotelId = 3,
                            Status = true,
                            TourId = 10,
                            UserId = 10
                        });
                });

            modelBuilder.Entity("AgencyWebApp.Domain.Models.Flight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AirPlaneName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("ArrivalTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DepartureTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("FlightNumber")
                        .HasColumnType("int");

                    b.Property<string>("FromCity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("FromLatitude")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("FromLongitude")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ToCity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ToLatitude")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ToLongitude")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Flights");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AirPlaneName = "Boeing 737-800",
                            ArrivalTime = new DateTime(2026, 5, 10, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = new DateTime(2026, 5, 10, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            FlightNumber = 101,
                            FromCity = "Moscow (DME)",
                            FromLatitude = 55.4103m,
                            FromLongitude = 37.9024m,
                            Price = 250.00m,
                            Status = "Scheduled",
                            ToCity = "Dushanbe (DYU)",
                            ToLatitude = 38.5433m,
                            ToLongitude = 68.8249m
                        },
                        new
                        {
                            Id = 2,
                            AirPlaneName = "Airbus A320",
                            ArrivalTime = new DateTime(2026, 5, 12, 16, 15, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = new DateTime(2026, 5, 12, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            FlightNumber = 202,
                            FromCity = "Istanbul (IST)",
                            FromLatitude = 41.2753m,
                            FromLongitude = 28.7519m,
                            Price = 320.00m,
                            Status = "Scheduled",
                            ToCity = "Dushanbe (DYU)",
                            ToLatitude = 38.5433m,
                            ToLongitude = 68.8249m
                        },
                        new
                        {
                            Id = 3,
                            AirPlaneName = "Boeing 737-300",
                            ArrivalTime = new DateTime(2026, 5, 15, 8, 50, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = new DateTime(2026, 5, 15, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            FlightNumber = 303,
                            FromCity = "Dushanbe (DYU)",
                            FromLatitude = 38.5433m,
                            FromLongitude = 68.8249m,
                            Price = 45.00m,
                            Status = "Active",
                            ToCity = "Khujand (LBD)",
                            ToLatitude = 40.2152m,
                            ToLongitude = 69.6944m
                        },
                        new
                        {
                            Id = 4,
                            AirPlaneName = "Boeing 737-800",
                            ArrivalTime = new DateTime(2026, 5, 19, 2, 30, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = new DateTime(2026, 5, 18, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            FlightNumber = 404,
                            FromCity = "Dubai (DXB)",
                            FromLatitude = 25.2532m,
                            FromLongitude = 55.3657m,
                            Price = 380.00m,
                            Status = "Scheduled",
                            ToCity = "Dushanbe (DYU)",
                            ToLatitude = 38.5433m,
                            ToLongitude = 68.8249m
                        },
                        new
                        {
                            Id = 5,
                            AirPlaneName = "Airbus A321",
                            ArrivalTime = new DateTime(2026, 5, 20, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = new DateTime(2026, 5, 20, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            FlightNumber = 505,
                            FromCity = "Tashkent (TAS)",
                            FromLatitude = 41.2575m,
                            FromLongitude = 69.2817m,
                            Price = 110.00m,
                            Status = "Active",
                            ToCity = "Dushanbe (DYU)",
                            ToLatitude = 38.5433m,
                            ToLongitude = 68.8249m
                        },
                        new
                        {
                            Id = 6,
                            AirPlaneName = "Boeing 737-800",
                            ArrivalTime = new DateTime(2026, 5, 22, 11, 45, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = new DateTime(2026, 5, 22, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            FlightNumber = 606,
                            FromCity = "Almaty (ALA)",
                            FromLatitude = 43.3520m,
                            FromLongitude = 77.0115m,
                            Price = 140.00m,
                            Status = "Scheduled",
                            ToCity = "Dushanbe (DYU)",
                            ToLatitude = 38.5433m,
                            ToLongitude = 68.8249m
                        },
                        new
                        {
                            Id = 7,
                            AirPlaneName = "Boeing 787 Dreamliner",
                            ArrivalTime = new DateTime(2026, 5, 26, 6, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = new DateTime(2026, 5, 25, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            FlightNumber = 707,
                            FromCity = "Frankfurt (FRA)",
                            FromLatitude = 50.0333m,
                            FromLongitude = 8.5705m,
                            Price = 650.00m,
                            Status = "Delayed",
                            ToCity = "Dushanbe (DYU)",
                            ToLatitude = 38.5433m,
                            ToLongitude = 68.8249m
                        },
                        new
                        {
                            Id = 8,
                            AirPlaneName = "Airbus A320",
                            ArrivalTime = new DateTime(2026, 5, 28, 7, 30, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = new DateTime(2026, 5, 28, 4, 0, 0, 0, DateTimeKind.Unspecified),
                            FlightNumber = 808,
                            FromCity = "Delhi (DEL)",
                            FromLatitude = 28.5562m,
                            FromLongitude = 77.1000m,
                            Price = 290.00m,
                            Status = "Scheduled",
                            ToCity = "Dushanbe (DYU)",
                            ToLatitude = 38.5433m,
                            ToLongitude = 68.8249m
                        },
                        new
                        {
                            Id = 9,
                            AirPlaneName = "Boeing 737-800",
                            ArrivalTime = new DateTime(2026, 6, 1, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = new DateTime(2026, 6, 1, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            FlightNumber = 909,
                            FromCity = "Munich (MUC)",
                            FromLatitude = 48.3537m,
                            FromLongitude = 11.7750m,
                            Price = 580.00m,
                            Status = "Active",
                            ToCity = "Dushanbe (DYU)",
                            ToLatitude = 38.5433m,
                            ToLongitude = 68.8249m
                        },
                        new
                        {
                            Id = 10,
                            AirPlaneName = "Embraer 190",
                            ArrivalTime = new DateTime(2026, 6, 3, 17, 30, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = new DateTime(2026, 6, 3, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            FlightNumber = 110,
                            FromCity = "Urumqi (URC)",
                            FromLatitude = 43.9071m,
                            FromLongitude = 87.4742m,
                            Price = 420.00m,
                            Status = "Scheduled",
                            ToCity = "Dushanbe (DYU)",
                            ToLatitude = 38.5433m,
                            ToLongitude = 68.8249m
                        });
                });

            modelBuilder.Entity("AgencyWebApp.Domain.Models.Hotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Hotels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "14 Rudaki Ave",
                            City = "Dushanbe",
                            Country = "Tajikistan",
                            Description = "A luxury 5-star hotel in the heart of the capital with traditional Tajik architecture.",
                            Latitude = 38.5737m,
                            Longitude = 68.7938m,
                            Name = "Dushanbe Serena Hotel",
                            PhotoUrl = "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=800",
                            Price = 160.00m,
                            Rating = 5,
                            Status = false
                        },
                        new
                        {
                            Id = 2,
                            Address = "26/1 Ismoili Somoni Ave",
                            City = "Dushanbe",
                            Country = "Tajikistan",
                            Description = "Modern lakeside hotel perfect for business and leisure travelers.",
                            Latitude = 38.5858m,
                            Longitude = 68.7725m,
                            Name = "Hyatt Regency Dushanbe",
                            PhotoUrl = "https://images.unsplash.com/photo-1551882547-ff43c63e1c04?auto=format&fit=crop&w=800",
                            Price = 185.00m,
                            Rating = 5,
                            Status = false
                        },
                        new
                        {
                            Id = 3,
                            Address = "63 Nisor Muhammad St",
                            City = "Dushanbe",
                            Country = "Tajikistan",
                            Description = "Boutique hotel featuring Tajik national fabrics and a beautiful garden.",
                            Latitude = 38.5601m,
                            Longitude = 68.8120m,
                            Name = "Atlas Hotel",
                            PhotoUrl = "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?auto=format&fit=crop&w=800",
                            Price = 85.00m,
                            Rating = 4,
                            Status = false
                        },
                        new
                        {
                            Id = 4,
                            Address = "22 Kamoli Khujandi St",
                            City = "Khujand",
                            Country = "Tajikistan",
                            Description = "The best apartments in Khujand city center with a river view.",
                            Latitude = 40.2825m,
                            Longitude = 69.6221m,
                            Name = "Armon Aparthotel",
                            PhotoUrl = "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=800",
                            Price = 75.00m,
                            Rating = 4,
                            Status = false
                        },
                        new
                        {
                            Id = 5,
                            Address = "15 Lenin St",
                            City = "Khujand",
                            Country = "Tajikistan",
                            Description = "Classic hotel located near the historical Panjshanbe Bazaar.",
                            Latitude = 40.2790m,
                            Longitude = 69.6300m,
                            Name = "Sugdiyon Hotel",
                            PhotoUrl = "https://images.unsplash.com/photo-1561501900-3701fa6a0864?auto=format&fit=crop&w=800",
                            Price = 55.00m,
                            Rating = 3,
                            Status = false
                        },
                        new
                        {
                            Id = 6,
                            Address = "Kalaikhumb Village",
                            City = "Darvoz",
                            Country = "Tajikistan",
                            Description = "The gateway to the Pamirs. Luxury comfort in a remote mountain setting.",
                            Latitude = 38.4571m,
                            Longitude = 70.7831m,
                            Name = "Karon Palace",
                            PhotoUrl = "https://images.unsplash.com/photo-1445019980597-93fa8acb246c?auto=format&fit=crop&w=800",
                            Price = 95.00m,
                            Rating = 5,
                            Status = false
                        },
                        new
                        {
                            Id = 7,
                            Address = "52 Lenin St",
                            City = "Khorog",
                            Country = "Tajikistan",
                            Description = "Famous Pamiri guesthouse known for its hospitality and traditional food.",
                            Latitude = 37.4896m,
                            Longitude = 71.5511m,
                            Name = "Lal Hotel",
                            PhotoUrl = "https://images.unsplash.com/photo-1582719478250-c89cae4df85b?auto=format&fit=crop&w=800",
                            Price = 65.00m,
                            Rating = 4,
                            Status = false
                        },
                        new
                        {
                            Id = 8,
                            Address = "10 Vahdat Ave",
                            City = "Bokhtar",
                            Country = "Tajikistan",
                            Description = "A comfortable central hotel for travelers exploring the Khatlon region.",
                            Latitude = 37.8364m,
                            Longitude = 68.7802m,
                            Name = "Grand Hotel Bokhtar",
                            PhotoUrl = "https://images.unsplash.com/photo-1495365200479-c4ed1d35e1aa?auto=format&fit=crop&w=800",
                            Price = 60.00m,
                            Rating = 3,
                            Status = false
                        },
                        new
                        {
                            Id = 9,
                            Address = "3 Loik Sherali St",
                            City = "Dushanbe",
                            Country = "Tajikistan",
                            Description = "Cozy and quiet boutique hotel located in a premium residential area.",
                            Latitude = 38.5900m,
                            Longitude = 68.7850m,
                            Name = "Seven In Boutique",
                            PhotoUrl = "https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=800",
                            Price = 90.00m,
                            Rating = 4,
                            Status = false
                        },
                        new
                        {
                            Id = 10,
                            Address = "48 Ayni St",
                            City = "Dushanbe",
                            Country = "Tajikistan",
                            Description = "Premium hospitality close to the airport and Dushanbe city center.",
                            Latitude = 38.5672m,
                            Longitude = 68.8051m,
                            Name = "Hilton Dushanbe",
                            PhotoUrl = "https://images.unsplash.com/photo-1590490360182-c33d57733427?auto=format&fit=crop&w=800",
                            Price = 145.00m,
                            Rating = 5,
                            Status = false
                        });
                });

            modelBuilder.Entity("AgencyWebApp.Domain.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FlightId")
                        .HasColumnType("int");

                    b.Property<int?>("HotelId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("TourId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FlightId");

                    b.HasIndex("HotelId");

                    b.HasIndex("TourId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HotelId = 7,
                            Text = "The Pamir Highway tour was a life-changing experience! Highly recommend.",
                            TourId = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 12, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HotelId = 1,
                            Text = "Dushanbe Serena Hotel is the best place to stay. Very professional staff.",
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FlightId = 1,
                            Text = "The flight from Moscow to Dushanbe was on time and very comfortable.",
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HotelId = 2,
                            Text = "Iskanderkul Lake is breathtaking. The tour guide was very knowledgeable.",
                            TourId = 4,
                            UserId = 4
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HotelId = 2,
                            Text = "Great service at Hyatt Regency. The breakfast selection was amazing.",
                            UserId = 5
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HotelId = 9,
                            Text = "Hulbuk Fortress is a hidden gem in Khatlon. A must-visit for history lovers.",
                            TourId = 9,
                            UserId = 6
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HotelId = 4,
                            Text = "Panjakent ruins are impressive. Seven Lakes tour was a bit tiring but worth it.",
                            TourId = 2,
                            UserId = 7
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FlightId = 3,
                            Text = "Somon Air flight to Khujand was quick and smooth. No complaints.",
                            UserId = 8
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2026, 1, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HotelId = 10,
                            Text = "The sanatorium in Khoja-Obigarm is unique. Perfect for health and relaxation.",
                            TourId = 5,
                            UserId = 9
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HotelId = 3,
                            Text = "Awesome day trip to Varzob Gorge. Great way to escape the city heat!",
                            TourId = 10,
                            UserId = 10
                        });
                });

            modelBuilder.Entity("AgencyWebApp.Domain.Models.Tour", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("StartLatitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal>("StartLongitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Tours");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "A legendary road trip through the high-altitude Pamir mountains and Khorog city.",
                            Duration = 7,
                            PhotoUrl = "https://images.unsplash.com/photo-1581414441460-7058866e409b?auto=format&fit=crop&w=800",
                            Price = 550.00m,
                            Rating = 5,
                            Region = "GBAO",
                            StartLatitude = 38.5737m,
                            StartLongitude = 68.7938m,
                            Status = true,
                            Title = "Pamir Highway Adventure"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Explore the ruins of Sarazm and the stunning Seven Lakes (Haft Kul).",
                            Duration = 3,
                            PhotoUrl = "https://images.unsplash.com/photo-1541829070764-84a7d30dee6b?auto=format&fit=crop&w=800",
                            Price = 120.00m,
                            Rating = 5,
                            Region = "Sughd",
                            StartLatitude = 39.4969m,
                            StartLongitude = 67.6103m,
                            Status = true,
                            Title = "Ancient Panjakent & Lakes"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Visit the National Museum, Ismoili Somoni monument, and local bazaars.",
                            Duration = 2,
                            PhotoUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/National_Museum_of_Tajikistan.jpg/800px-National_Museum_of_Tajikistan.jpg",
                            Price = 85.00m,
                            Rating = 4,
                            Region = "Dushanbe",
                            StartLatitude = 38.5858m,
                            StartLongitude = 68.7725m,
                            Status = true,
                            Title = "Dushanbe City Weekend"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Visit the lake of Alexander the Great and the famous 'Fan Niagara' waterfall.",
                            Duration = 3,
                            PhotoUrl = "https://images.unsplash.com/photo-1563290328-9710279603e8?auto=format&fit=crop&w=800",
                            Price = 150.00m,
                            Rating = 5,
                            Region = "Fann Mountains",
                            StartLatitude = 39.0833m,
                            StartLongitude = 68.3667m,
                            Status = true,
                            Title = "Iskanderkul Lake Escape"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Relax at the famous Soviet-era balneological steam sanatorium.",
                            Duration = 10,
                            PhotoUrl = "https://images.unsplash.com/photo-1544161515-4ab6ce6db874?auto=format&fit=crop&w=800",
                            Price = 300.00m,
                            Rating = 4,
                            Region = "Varzob",
                            StartLatitude = 38.8953m,
                            StartLongitude = 68.7914m,
                            Status = true,
                            Title = "Khoja-Obigarm Wellness"
                        },
                        new
                        {
                            Id = 6,
                            Description = "High-altitude nomadic life, yaks, and moon-like landscapes near the Chinese border.",
                            Duration = 12,
                            PhotoUrl = "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=800",
                            Price = 750.00m,
                            Rating = 5,
                            Region = "East Pamir",
                            StartLatitude = 38.1702m,
                            StartLongitude = 73.9647m,
                            Status = true,
                            Title = "Murghab: Roof of the World"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Historical tour to the 5th-century fortress and the Syr Darya river.",
                            Duration = 2,
                            PhotoUrl = "https://images.unsplash.com/photo-1523393160341-9c869066666d?auto=format&fit=crop&w=800",
                            Price = 90.00m,
                            Rating = 4,
                            Region = "Sughd",
                            StartLatitude = 40.2825m,
                            StartLongitude = 69.6221m,
                            Status = true,
                            Title = "Khujand Fortress Tour"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Eco-trip to one of the most beautiful and remote valleys in Tajikistan.",
                            Duration = 5,
                            PhotoUrl = "https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=800",
                            Price = 210.00m,
                            Rating = 5,
                            Region = "Khatlon",
                            StartLatitude = 38.2167m,
                            StartLongitude = 69.8333m,
                            Status = true,
                            Title = "Sari Khosor Nature"
                        },
                        new
                        {
                            Id = 9,
                            Description = "A day trip to the reconstructed palace of the medieval Kings of Khuttal.",
                            Duration = 1,
                            PhotoUrl = "https://images.unsplash.com/photo-1590059132218-22ca52103723?auto=format&fit=crop&w=800",
                            Price = 45.00m,
                            Rating = 4,
                            Region = "Khatlon",
                            StartLatitude = 37.7772m,
                            StartLongitude = 69.5539m,
                            Status = true,
                            Title = "Hulbuk Fortress History"
                        },
                        new
                        {
                            Id = 10,
                            Description = "The most popular recreation area near Dushanbe for rivers and hiking.",
                            Duration = 1,
                            PhotoUrl = "https://images.unsplash.com/photo-1470770841072-f978cf4d019e?auto=format&fit=crop&w=800",
                            Price = 35.00m,
                            Rating = 5,
                            Region = "RRP",
                            StartLatitude = 38.7411m,
                            StartLongitude = 68.8144m,
                            Status = true,
                            Title = "Varzob Gorge Day Trip"
                        });
                });

            modelBuilder.Entity("AgencyWebApp.Domain.Models.TourPoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Latitude")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int>("TourId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TourId");

                    b.ToTable("TourPoint");
                });

            modelBuilder.Entity("AgencyWebApp.Domain.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("HomeLatitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal?>("HomeLongitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "alisher@mail.tj",
                            FullName = "Алишер Саидов",
                            Password = "$2a$11$RFSOOYEA.tpejpq8VE0miuEEBYGnfOLcmESifkA4.d6cXY7zUbHmq",
                            Role = 1
                        },
                        new
                        {
                            Id = 2,
                            Email = "madina@gmail.com",
                            FullName = "Мадина Каримова",
                            Password = "$2a$11$RFSOOYEA.tpejpq8VE0miuEEBYGnfOLcmESifkA4.d6cXY7zUbHmq",
                            Role = 1
                        },
                        new
                        {
                            Id = 3,
                            Email = "bakhtier@list.ru",
                            FullName = "Бахтиёр Назаров",
                            Password = "$2a$11$RFSOOYEA.tpejpq8VE0miuEEBYGnfOLcmESifkA4.d6cXY7zUbHmq",
                            Role = 1
                        },
                        new
                        {
                            Id = 4,
                            Email = "nigina@yandex.ru",
                            FullName = "Нигина Рахимова",
                            Password = "$2a$11$RFSOOYEA.tpejpq8VE0miuEEBYGnfOLcmESifkA4.d6cXY7zUbHmq",
                            Role = 1
                        },
                        new
                        {
                            Id = 5,
                            Email = "parviz@outlook.com",
                            FullName = "Парвиз Ходжаев",
                            Password = "$2a$11$RFSOOYEA.tpejpq8VE0miuEEBYGnfOLcmESifkA4.d6cXY7zUbHmq",
                            Role = 1
                        },
                        new
                        {
                            Id = 6,
                            Email = "zarina@mail.tj",
                            FullName = "Зарина Олимова",
                            Password = "$2a$11$RFSOOYEA.tpejpq8VE0miuEEBYGnfOLcmESifkA4.d6cXY7zUbHmq",
                            Role = 1
                        },
                        new
                        {
                            Id = 7,
                            Email = "rustam@google.com",
                            FullName = "Рустам Эшонов",
                            Password = "$2a$11$RFSOOYEA.tpejpq8VE0miuEEBYGnfOLcmESifkA4.d6cXY7zUbHmq",
                            Role = 1
                        },
                        new
                        {
                            Id = 8,
                            Email = "sitora@inbox.ru",
                            FullName = "Ситора Джумаева",
                            Password = "$2a$11$RFSOOYEA.tpejpq8VE0miuEEBYGnfOLcmESifkA4.d6cXY7zUbHmq",
                            Role = 1
                        },
                        new
                        {
                            Id = 9,
                            Email = "firdavs@rambler.ru",
                            FullName = "Фирдавс Гафуров",
                            Password = "$2a$11$RFSOOYEA.tpejpq8VE0miuEEBYGnfOLcmESifkA4.d6cXY7zUbHmq",
                            Role = 1
                        },
                        new
                        {
                            Id = 10,
                            Email = "lola@tj-travel.tj",
                            FullName = "Лола Шарипова",
                            Password = "$2a$11$RFSOOYEA.tpejpq8VE0miuEEBYGnfOLcmESifkA4.d6cXY7zUbHmq",
                            Role = 1
                        });
                });

            modelBuilder.Entity("AgencyWebApp.Domain.Models.Booking", b =>
                {
                    b.HasOne("AgencyWebApp.Domain.Models.Flight", "Flight")
                        .WithMany("Bookings")
                        .HasForeignKey("FlightId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AgencyWebApp.Domain.Models.Hotel", "Hotel")
                        .WithMany("Bookings")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AgencyWebApp.Domain.Models.Tour", "Tour")
                        .WithMany("Bookings")
                        .HasForeignKey("TourId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AgencyWebApp.Domain.Models.User", "User")
                        .WithMany("Bookings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Flight");

                    b.Navigation("Hotel");

                    b.Navigation("Tour");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AgencyWebApp.Domain.Models.Review", b =>
                {
                    b.HasOne("AgencyWebApp.Domain.Models.Flight", "Flight")
                        .WithMany("Reviews")
                        .HasForeignKey("FlightId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AgencyWebApp.Domain.Models.Hotel", "Hotel")
                        .WithMany("Reviews")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AgencyWebApp.Domain.Models.Tour", "Tour")
                        .WithMany("Reviews")
                        .HasForeignKey("TourId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AgencyWebApp.Domain.Models.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Flight");

                    b.Navigation("Hotel");

                    b.Navigation("Tour");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AgencyWebApp.Domain.Models.TourPoint", b =>
                {
                    b.HasOne("AgencyWebApp.Domain.Models.Tour", "Tour")
                        .WithMany("TourPoints")
                        .HasForeignKey("TourId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tour");
                });

            modelBuilder.Entity("AgencyWebApp.Domain.Models.Flight", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("AgencyWebApp.Domain.Models.Hotel", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("AgencyWebApp.Domain.Models.Tour", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Reviews");

                    b.Navigation("TourPoints");
                });

            modelBuilder.Entity("AgencyWebApp.Domain.Models.User", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
